language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm start &
  - npm run e2e
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
