version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
        environment:
          # our app's alias, new deployments after testing
          # will be pointed at this alias
          ALIAS: test-results-server-aa7190
          # full aliased url
          FULL_URL: https://test-results-server-aa7190.now.sh
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - run: npm install now-pipeline@1.8.0

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
      - run:
          name: Stop build if any files changed after linting
          command: $(npm bin)/stop-build
      - run:
          name: Save commit and version information
          command: npm run build-info
      - run:
          name: Show included files
          command: npm run size

      - run:
          name: Start local server
          command: npm start
          background: true
      - run:
          name: Test against local server
          command: npm run e2e

      - run:
          name: Deploy new version and test against it
          command: $(npm bin)/now-pipeline --alias $ALIAS --test 'npm run e2e'
      - run:
          name: Test against the new alias
          command: NOW_URL=$FULL_URL/version npm run e2e
      - run:
          name: Prune other deploys
          command: $(npm bin)/now-pipeline-prune


